###
## ACTIVITY ################################
GET http://localhost:3000/activities

###

GET http://localhost:3000/activities/614565c5fad5998553b03362

###

POST http://localhost:3000/activities
Content-Type: : application/json

{
    "activityName": "BioInfo",
    "description": "L3S1 Module"
}

###

DELETE http://localhost:3000/activities/6144d7210d23b6e550735521

###

PATCH http://localhost:3000/activities/614565dafad5998553b03365
Content-Type: application/json

{
    "activityName": "Automata Theory"
}


### USERS ######################################################
###
GET http://localhost:3000/users

###

GET http://localhost:3000/users/614574e8339c997d94ef84e2


### GROUPS ########################################################
###
GET http://localhost:3000/groups

###
GET http://localhost:3000/groups/6149d25a013862749ae85cb9

###
POST http://localhost:3000/groups
Content-Type: application/json

{
    "groupName": "akirao",
    "adminId": "G0002"
}

### LOGS ############################################################
###
GET http://localhost:3000/logs

###

GET http://localhost:3000/logs/61478567fffc4621652debf4
